#!/bin/bash

read -n1 -rep 'Would you like to install the packages? (Y,n)' INST
if [[ $INST == "Y" || $INST == "y" ]]; then
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si --noconfirm
    cd ..
    yay -S --noconfirm --needed - < pkg.lst
    cp -R ./assets/* ~/.config/
    mkdir ~/Pictures
    cp -R ./Wallpapers ~/Pictures
    chmod +x ~/.config/hypr/scripts/XDPH
    else
        exit
fi